import React, { createContext, useContext, useState } from 'react'

const LangContext = createContext()

const translations = {
  // Navbar
  home: { en: 'Home', th: 'หน้าแรก' },
  createQuestion: { en: 'Create Question', th: 'สร้างคำถาม' },
  takeExam: { en: 'Take Exam', th: 'ทำข้อสอบ' },
  createExam: { en: 'Create Exam', th: 'สร้างชุดข้อสอบ' },
  student: { en: 'Student', th: 'นักศึกษา' },
  manage: { en: 'Manage Exam', th: 'จัดการข้อสอบ' },
  results: { en: 'Results', th: 'ผลสอบ' },
  analytics: { en: 'Analytics', th: 'วิเคราะห์' },
  moderator: { en: 'Moderator', th: 'ผู้ตรวจสอบ' },
  users: { en: 'Users', th: 'ผู้ใช้งาน' },
  logout: { en: 'Logout', th: 'ออกจากระบบ' },
  login: { en: 'Login', th: 'เข้าสู่ระบบ' },
  signedIn: { en: 'Signed in', th: 'เข้าสู่ระบบแล้ว' },

  // Session expired overlay
  sessionExpired: { en: 'Session Expired', th: 'เซสชันหมดอายุ' },
  sessionExpiredMsg: { en: 'Your session has expired. Please log in again to continue. Your form data is preserved.', th: 'เซสชันของคุณหมดอายุ กรุณาเข้าสู่ระบบอีกครั้งเพื่อดำเนินการต่อ ข้อมูลในฟอร์มของคุณยังคงอยู่' },
  reLogin: { en: 'Log In Again', th: 'เข้าสู่ระบบอีกครั้ง' },
  sessionRestored: { en: 'Session restored! You can now retry your action.', th: 'เข้าสู่ระบบสำเร็จ! คุณสามารถดำเนินการต่อได้' },

  // Login page
  loginTitle: { en: 'Chomthong Hospital Medical Learning Platform', th: 'ระบบการเรียนรู้ทางการแพทย์ โรงพยาบาลจอมทอง' },
  loginSubtitle: { en: 'Login', th: 'เข้าสู่ระบบ' },
  email: { en: 'Email', th: 'อีเมล' },
  password: { en: 'Password', th: 'รหัสผ่าน' },
  loginBtn: { en: 'Login', th: 'เข้าสู่ระบบ' },
  loginSuccess: { en: 'Logged in — token saved', th: 'เข้าสู่ระบบสำเร็จ' },
  loginFailed: { en: 'Login failed', th: 'เข้าสู่ระบบไม่สำเร็จ' },
  testAccounts: { en: 'Test Accounts', th: 'บัญชีทดสอบ' },

  // Admin User Management
  adminUserMgmt: { en: '👥 Admin User Management', th: '👥 จัดการผู้ใช้งาน' },
  back: { en: 'Back', th: 'กลับ' },
  createNewUser: { en: 'Create New User', th: 'สร้างผู้ใช้ใหม่' },
  editUser: { en: 'Edit User', th: 'แก้ไขผู้ใช้' },
  name: { en: 'Name', th: 'ชื่อ' },
  fullName: { en: 'Full name', th: 'ชื่อ-นามสกุล' },
  passwordOptional: { en: '(leave blank to keep current)', th: '(เว้นว่างไว้หากไม่เปลี่ยน)' },
  hospital: { en: 'Hospital', th: 'โรงพยาบาล' },
  province: { en: 'Province', th: 'จังหวัด' },
  lineId: { en: 'Line ID', th: 'ไลน์ไอดี' },
  role: { en: 'Role', th: 'บทบาท' },
  profilePicture: { en: 'Profile Picture', th: 'รูปโปรไฟล์' },
  maxFileSize: { en: 'Max 5MB. JPEG, PNG, GIF, or WebP.', th: 'สูงสุด 5MB รองรับ JPEG, PNG, GIF, WebP' },
  updateUser: { en: 'Update User', th: 'อัปเดตผู้ใช้' },
  createUser: { en: 'Create User', th: 'สร้างผู้ใช้' },
  cancel: { en: 'Cancel', th: 'ยกเลิก' },
  existingUsers: { en: 'Existing Users', th: 'ผู้ใช้ทั้งหมด' },
  picture: { en: 'Picture', th: 'รูป' },
  actions: { en: 'Actions', th: 'จัดการ' },
  edit: { en: 'Edit', th: 'แก้ไข' },
  delete: { en: 'Delete', th: 'ลบ' },
  confirmDelete: { en: 'Are you sure you want to delete this user?', th: 'คุณต้องการลบผู้ใช้นี้หรือไม่?' },
  userCreated: { en: 'User created successfully', th: 'สร้างผู้ใช้สำเร็จ' },
  userUpdated: { en: 'User updated successfully', th: 'อัปเดตผู้ใช้สำเร็จ' },
  userDeleted: { en: 'User deleted successfully', th: 'ลบผู้ใช้สำเร็จ' },
  userRolesGuide: { en: 'User Roles Guide', th: 'คู่มือบทบาทผู้ใช้' },
  loadingUsers: { en: 'Loading users...', th: 'กำลังโหลดผู้ใช้...' },
  noUsers: { en: 'No users yet. Create one to get started.', th: 'ยังไม่มีผู้ใช้ สร้างผู้ใช้เพื่อเริ่มต้น' },
  required: { en: 'required', th: 'จำเป็น' },
  nameEmailRoleRequired: { en: 'Name, email, and role are required', th: 'ชื่อ อีเมล และบทบาท จำเป็นต้องกรอก' },
  passwordRequired: { en: 'Password is required for new users', th: 'รหัสผ่านจำเป็นสำหรับผู้ใช้ใหม่' },

  // Role labels
  roleStudent: { en: 'Student', th: 'นักศึกษา' },
  roleResident: { en: 'Resident', th: 'แพทย์ประจำบ้าน' },
  roleFellow: { en: 'Fellow', th: 'แพทย์ต่อยอด' },
  roleClinician: { en: 'Clinician (Question Creator)', th: 'อาจารย์แพทย์ (ผู้ออกข้อสอบ)' },
  roleModerator: { en: 'Moderator (Approver)', th: 'ผู้ตรวจสอบ (ผู้อนุมัติ)' },
  roleAdmin: { en: 'Administrator', th: 'ผู้ดูแลระบบ' },

  // Role descriptions
  roleStudentDesc: { en: 'Can take exams and view personal statistics and reports', th: 'ทำข้อสอบและดูสถิติผลการเรียนรู้ส่วนบุคคล' },
  roleResidentDesc: { en: 'Can take exams, create questions, and track progress', th: 'ทำข้อสอบ สร้างคำถาม และติดตามความก้าวหน้า' },
  roleFellowDesc: { en: 'Can take exams, create questions and exams, and track progress', th: 'ทำข้อสอบ สร้างคำถามและชุดข้อสอบ ติดตามความก้าวหน้า' },
  roleClinicianDesc: { en: 'Can create and upload exam questions for moderation', th: 'สร้างและอัปโหลดคำถามเพื่อส่งตรวจสอบ' },
  roleModeratorDesc: { en: 'Can approve or reject questions submitted by clinicians', th: 'อนุมัติหรือส่งกลับคำถามที่ส่งมาจากอาจารย์แพทย์' },
  roleAdminDesc: { en: 'Can manage all users, view analytics, and system settings', th: 'จัดการผู้ใช้ทั้งหมด ดูวิเคราะห์ และตั้งค่าระบบ' },

  // Common
  clickToClose: { en: 'Click anywhere to close', th: 'คลิกที่ใดก็ได้เพื่อปิด' },
  error: { en: 'Error', th: 'ข้อผิดพลาด' },
  failed: { en: 'Failed', th: 'ล้มเหลว' },
  loading: { en: 'Loading...', th: 'กำลังโหลด...' },
  submit: { en: 'Submit', th: 'ส่ง' },
  save: { en: 'Save', th: 'บันทึก' },

  // HomePage - Hero
  heroSubtitle: { en: 'CHOMTHONG HOSPITAL · CENTER OF EXCELLENCE IN MEDICAL EDUCATION', th: 'โรงพยาบาลจอมทอง · ศูนย์ความเป็นเลิศด้านการศึกษาทางการแพทย์' },
  heroWelcome: { en: 'Welcome', th: 'ยินดีต้อนรับ' },
  heroTitle: { en: 'Knowledge Management for Medical Excellence', th: 'การจัดการความรู้เพื่อความเป็นเลิศทางการแพทย์' },
  heroDesc: { en: 'Empowering healthcare professionals through evidence-based learning, continuous assessment, and data-driven professional development — building a culture of excellence at Chomthong Hospital.', th: 'เสริมศักยภาพบุคลากรสุขภาพด้วยการเรียนรู้เชิงประจักษ์ การประเมินอย่างต่อเนื่อง และการพัฒนาวิชาชีพจากข้อมูล — สร้างวัฒนธรรมแห่งความเป็นเลิศ ณ โรงพยาบาลจอมทอง' },
  heroStartExam: { en: 'Start Exam', th: 'เริ่มทำข้อสอบ' },
  heroCreateQ: { en: 'Create Question', th: 'สร้างคำถาม' },
  heroReviewQueue: { en: 'Review Queue', th: 'ตรวจสอบคำถาม' },
  heroManageSystem: { en: 'Manage System', th: 'จัดการระบบ' },
  heroSignIn: { en: 'Sign In', th: 'เข้าสู่ระบบ' },

  // HomePage - KM Metrics
  kmMetricsTitle: { en: 'Knowledge Management Impact', th: 'ผลลัพธ์การจัดการความรู้' },
  kmMetricsDesc: { en: 'Real outcomes from our commitment to continuous medical education', th: 'ผลลัพธ์จริงจากความมุ่งมั่นในการศึกษาทางการแพทย์อย่างต่อเนื่อง' },
  kmQuestionBank: { en: 'Question Bank Items', th: 'คำถามในคลัง' },
  kmExamsCreated: { en: 'Exams Created', th: 'ชุดข้อสอบที่สร้าง' },
  kmActiveUsers: { en: 'Active Learners', th: 'ผู้เรียนที่ใช้งาน' },
  kmSpecialties: { en: 'Medical Specialties', th: 'สาขาเฉพาะทาง' },

  // HomePage - Why Section
  whyTitle: { en: 'Why Chomthong Hospital KM Platform?', th: 'ทำไมต้องเลือกระบบ KM โรงพยาบาลจอมทอง?' },
  whyEvidence: { en: 'Evidence-Based Content', th: 'เนื้อหาอิงหลักฐาน' },
  whyEvidenceDesc: { en: 'Every question undergoes rigorous peer review by experienced clinicians and moderators, ensuring the highest standard of medical accuracy.', th: 'ทุกคำถามผ่านการตรวจสอบอย่างเข้มงวดโดยแพทย์ผู้เชี่ยวชาญและผู้ตรวจสอบ เพื่อมาตรฐานความถูกต้องทางการแพทย์สูงสุด' },
  whyAnalytics: { en: 'Smart Learning Analytics', th: 'การวิเคราะห์การเรียนรู้อัจฉริยะ' },
  whyAnalyticsDesc: { en: 'Track individual progress, identify knowledge gaps, and receive personalized insights to guide your professional development journey.', th: 'ติดตามความก้าวหน้ารายบุคคล ระบุจุดที่ต้องพัฒนา และรับข้อมูลเชิงลึกเพื่อชี้นำเส้นทางการพัฒนาวิชาชีพ' },
  whyMultiRole: { en: 'Multi-Role Collaboration', th: 'ความร่วมมือหลายบทบาท' },
  whyMultiRoleDesc: { en: 'Students, residents, fellows, clinicians, moderators, and administrators work together in a seamless ecosystem of knowledge creation and validation.', th: 'นักศึกษา แพทย์ประจำบ้าน แพทย์ต่อยอด อาจารย์แพทย์ ผู้ตรวจสอบ และผู้ดูแลระบบ ร่วมกันสร้างระบบนิเวศการเรียนรู้อย่างไร้รอยต่อ' },
  whyBilingual: { en: 'Bilingual Thai-English', th: 'สองภาษา ไทย-อังกฤษ' },
  whyBilingualDesc: { en: 'Full Thai and English support throughout the platform, making medical education accessible and comfortable for all team members.', th: 'รองรับภาษาไทยและอังกฤษตลอดทั้งระบบ ทำให้การศึกษาทางการแพทย์เข้าถึงง่ายและสะดวกสบายสำหรับทุกคน' },
  whyContinuous: { en: 'Continuous Quality Improvement', th: 'พัฒนาคุณภาพอย่างต่อเนื่อง' },
  whyContinuousDesc: { en: 'Our KM cycle — Create, Review, Assess, Analyze, Improve — drives ongoing enhancement of both content quality and learner outcomes.', th: 'วงจร KM ของเรา — สร้าง ตรวจสอบ ประเมิน วิเคราะห์ ปรับปรุง — ขับเคลื่อนการพัฒนาคุณภาพเนื้อหาและผลลัพธ์ผู้เรียนอย่างต่อเนื่อง' },
  whySecure: { en: 'Secure & Professional', th: 'ปลอดภัยและเป็นมืออาชีพ' },
  whySecureDesc: { en: 'Enterprise-grade authentication, role-based access control, and audit logging to protect sensitive medical education data.', th: 'ระบบยืนยันตัวตนระดับองค์กร การควบคุมสิทธิ์ตามบทบาท และบันทึกตรวจสอบ เพื่อปกป้องข้อมูลการศึกษาทางการแพทย์' },

  // HomePage - KM Cycle
  kmCycleTitle: { en: 'Our Knowledge Management Cycle', th: 'วงจรการจัดการความรู้ของเรา' },
  kmCycleDesc: { en: 'A systematic approach to building and maintaining medical knowledge excellence', th: 'แนวทางเป็นระบบในการสร้างและรักษาความเป็นเลิศด้านความรู้ทางการแพทย์' },
  kmStep1: { en: 'Create', th: 'สร้าง' },
  kmStep1Desc: { en: 'Clinicians create evidence-based questions with detailed rationale', th: 'อาจารย์แพทย์สร้างคำถามอิงหลักฐานพร้อมเหตุผลโดยละเอียด' },
  kmStep2: { en: 'Review', th: 'ตรวจสอบ' },
  kmStep2Desc: { en: 'Moderators ensure quality, accuracy, and educational value', th: 'ผู้ตรวจสอบดูแลคุณภาพ ความถูกต้อง และคุณค่าทางการศึกษา' },
  kmStep3: { en: 'Assess', th: 'ประเมิน' },
  kmStep3Desc: { en: 'Learners take structured exams to measure competency', th: 'ผู้เรียนทำข้อสอบเชิงโครงสร้างเพื่อวัดสมรรถนะ' },
  kmStep4: { en: 'Analyze', th: 'วิเคราะห์' },
  kmStep4Desc: { en: 'Data-driven insights reveal trends and knowledge gaps', th: 'ข้อมูลเชิงลึกเผยแนวโน้มและจุดที่ต้องเสริมความรู้' },
  kmStep5: { en: 'Improve', th: 'ปรับปรุง' },
  kmStep5Desc: { en: 'Continuous refinement of content and learning strategies', th: 'ปรับปรุงเนื้อหาและกลยุทธ์การเรียนรู้อย่างต่อเนื่อง' },

  // HomePage - Learning Stats
  learningSnapshot: { en: 'Your Learning Dashboard', th: 'แดชบอร์ดการเรียนรู้ของคุณ' },
  examsCompleted: { en: 'Exams Taken', th: 'จำนวนครั้งที่สอบ' },
  avgScore: { en: 'Average Score', th: 'คะแนนเฉลี่ย' },
  bestScore: { en: 'Best Score', th: 'คะแนนสูงสุด' },
  improvement: { en: 'Improvement', th: 'พัฒนาการ' },

  // HomePage - Role Panels
  learnerPath: { en: 'Learner Path', th: 'เส้นทางผู้เรียน' },
  residentPath: { en: 'Resident Path', th: 'เส้นทางแพทย์ประจำบ้าน' },
  fellowPath: { en: 'Fellow Path', th: 'เส้นทางแพทย์ต่อยอด' },
  clinicianWorkflow: { en: 'Clinician Workflow', th: 'เส้นทางผู้ออกข้อสอบ' },
  moderatorWorkflow: { en: 'Moderator Workflow', th: 'เส้นทางผู้ตรวจ' },
  adminControl: { en: 'Admin Control', th: 'เส้นทางผู้ดูแลระบบ' },
  studentBullet1: { en: 'Take exams and track your progress', th: 'ทำข้อสอบและติดตามพัฒนาการของตนเอง' },
  studentBullet2: { en: 'Identify strengths and improvement areas', th: 'ดูจุดแข็ง-จุดที่ต้องพัฒนา' },
  studentBullet3: { en: 'Access detailed performance reports', th: 'เข้าถึงรายงานผลแบบละเอียด' },
  residentBullet1: { en: 'Take exams and track your progress', th: 'ทำข้อสอบและติดตามพัฒนาการ' },
  residentBullet2: { en: 'Create questions for moderation', th: 'สร้างคำถามเพื่อเสนออนุมัติ' },
  residentBullet3: { en: 'Manage your own question bank', th: 'จัดการคำถามของตนเอง' },
  fellowBullet1: { en: 'Take exams and track your progress', th: 'ทำข้อสอบและติดตามพัฒนาการ' },
  fellowBullet2: { en: 'Create questions and exams', th: 'สร้างคำถามและชุดข้อสอบ' },
  fellowBullet3: { en: 'Manage your items', th: 'จัดการคำถามและข้อสอบของตนเอง' },
  clinicianBullet1: { en: 'Create high-quality questions with rationale', th: 'สร้างคำถามคุณภาพสูงพร้อมเหตุผลทางวิชาการ' },
  clinicianBullet2: { en: 'Track moderation status', th: 'ติดตามสถานะการพิจารณาโดยผู้ตรวจ' },
  clinicianBullet3: { en: 'Manage your own question bank efficiently', th: 'จัดการคลังคำถามของตนเองได้สะดวก' },
  moderatorBullet1: { en: 'Review quality before publication', th: 'ตรวจคุณภาพคำถามก่อนเผยแพร่' },
  moderatorBullet2: { en: 'Approve or return with feedback', th: 'อนุมัติหรือส่งกลับพร้อมข้อเสนอแนะ' },
  moderatorBullet3: { en: 'Maintain content standards', th: 'ช่วยยกระดับมาตรฐานเนื้อหา' },
  adminBullet1: { en: 'Manage users and permissions', th: 'จัดการผู้ใช้งานและสิทธิ์' },
  adminBullet2: { en: 'Monitor platform usage', th: 'ติดตามภาพรวมการใช้งานระบบ' },
  adminBullet3: { en: 'Support learning ecosystem growth', th: 'สนับสนุนการเติบโตของชุมชนการเรียนรู้' },
  startExamBtn: { en: 'Start Exam', th: 'เริ่มทำข้อสอบ' },
  viewStats: { en: 'View Statistics', th: 'ดูสถิติ' },
  createQuestionBtn: { en: 'Create Question', th: 'สร้างคำถาม' },
  manageItems: { en: 'Manage Items', th: 'จัดการรายการ' },
  reviewQueue: { en: 'Review Queue', th: 'คิวตรวจสอบ' },
  viewAnalytics: { en: 'View Analytics', th: 'ดูภาพรวม' },
  manageUsersBtn: { en: 'Manage Users', th: 'จัดการผู้ใช้' },
  dashboard: { en: 'Dashboard', th: 'แดชบอร์ด' },

  // HomePage - CTA
  ctaTitle: { en: 'Ready to Elevate Your Medical Expertise?', th: 'พร้อมยกระดับความเชี่ยวชาญทางการแพทย์แล้วหรือยัง?' },
  ctaDesc: { en: 'Join Chomthong Hospital\'s knowledge management community and experience professional medical education at its finest.', th: 'ร่วมเป็นส่วนหนึ่งของชุมชนจัดการความรู้ โรงพยาบาลจอมทอง และสัมผัสการศึกษาทางการแพทย์ระดับมืออาชีพ' },
  ctaGetStarted: { en: 'Get Started', th: 'เริ่มต้นใช้งาน' },

  // HomePage - Network & Team Showcase
  networkTitle: { en: 'Our Hospital Network', th: 'เครือข่ายโรงพยาบาลของเรา' },
  networkDesc: { en: 'Healthcare institutions collaborating on our knowledge management platform', th: 'สถาบันสุขภาพที่ร่วมมือกันบนแพลตฟอร์มจัดการความรู้ของเรา' },
  networkMembers: { en: 'members', th: 'สมาชิก' },
  teamTitle: { en: 'Our Expert Team', th: 'ทีมผู้เชี่ยวชาญของเรา' },
  teamDesc: { en: 'Dedicated healthcare professionals driving knowledge management and medical education excellence', th: 'บุคลากรทางการแพทย์ผู้ทุ่มเทขับเคลื่อนการจัดการความรู้และความเป็นเลิศด้านการศึกษาทางการแพทย์' },
  teamRoleAdmin: { en: 'System Administrator', th: 'ผู้ดูแลระบบ' },
  teamRoleModerator: { en: 'Content Reviewer', th: 'ผู้ตรวจสอบเนื้อหา' },
  teamRoleClinician: { en: 'Question Creator', th: 'ผู้ออกข้อสอบ' },
  teamRoleFellow: { en: 'Fellow · Question Creator', th: 'แพทย์ต่อยอด · ผู้ออกข้อสอบ' },
  communityTitle: { en: 'Learning Community', th: 'ชุมชนการเรียนรู้' },
  communityDesc: { en: 'Our platform brings together learners and educators from multiple roles', th: 'แพลตฟอร์มของเรารวบรวมผู้เรียนและผู้สอนจากหลากหลายบทบาท' },
  networkHospitals: { en: 'hospitals', th: 'โรงพยาบาล' },
  clickToView: { en: 'Click to view details', th: 'คลิกเพื่อดูรายละเอียด' },
  hospitalProvinceDetail: { en: 'Hospital & Province Detail', th: 'รายละเอียดโรงพยาบาลและจังหวัด' },
  noHospitalData: { en: 'No hospital data available', th: 'ไม่มีข้อมูลโรงพยาบาล' },

  // ExamBuilder
  ebCreateExam: { en: 'Create Exam', th: 'สร้างชุดข้อสอบ' },
  ebExamName: { en: 'Name of exam *', th: 'ชื่อข้อสอบ *' },
  ebSpecialty: { en: 'Specialty *', th: 'สาขาเฉพาะทาง *' },
  ebSubspecialty: { en: 'Subspecialty *', th: 'สาขาย่อย *' },
  ebSelectSpecialty: { en: '-- select major specialty --', th: '-- เลือกสาขาหลัก --' },
  ebAllSpecialties: { en: '✱ Comprehensive (All Specialties)', th: '✱ ครอบคลุม (ทุกสาขา)' },
  ebSelectSubspecialty: { en: '-- select subspecialty --', th: '-- เลือกสาขาย่อย --' },
  ebAllSubspecialties: { en: '✱ All Subspecialties', th: '✱ ทุกสาขาย่อย' },
  ebPassingScore: { en: 'Passing Score (%) *', th: 'คะแนนผ่านขั้นต่ำ (%) *' },
  ebPassingScoreHint: { en: 'Students must score at least {0}% to pass', th: 'ผู้สอบต้องได้คะแนนอย่างน้อย {0}% จึงจะผ่าน' },
  ebSelectionMode: { en: 'Selection mode:', th: 'รูปแบบการเลือก:' },
  ebRandom: { en: 'Random', th: 'สุ่ม' },
  ebManual: { en: 'Manual', th: 'กำหนดเอง' },
  ebDifficulty: { en: 'Difficulty:', th: 'ระดับความยาก:' },
  ebEasy: { en: 'Easy (1-2)', th: 'ง่าย (1-2)' },
  ebMedium: { en: 'Medium (3)', th: 'ปานกลาง (3)' },
  ebDifficult: { en: 'Difficult (4)', th: 'ยาก (4)' },
  ebExtreme: { en: 'Extreme difficult (5)', th: 'ยากมาก (5)' },
  ebUseDistribution: { en: 'Use distribution', th: 'ใช้สัดส่วน' },
  ebNumQuestions: { en: 'Number of questions:', th: 'จำนวนข้อ:' },
  ebDistHint: { en: 'Difficulty distribution (auto-adjusts to sum to 100%)', th: 'สัดส่วนความยาก (ปรับอัตโนมัติให้รวม 100%)' },
  ebLevel12: { en: 'Level 1–2', th: 'ระดับ 1–2' },
  ebLevel3: { en: 'Level 3', th: 'ระดับ 3' },
  ebLevel4: { en: 'Level 4', th: 'ระดับ 4' },
  ebLevel5: { en: 'Level 5', th: 'ระดับ 5' },
  ebTotal: { en: 'Total:', th: 'รวม:' },
  ebSelectQHint: { en: 'Select questions to include in exam. Shows approved questions matching specialty + difficulty filters.', th: 'เลือกคำถามสำหรับข้อสอบ แสดงคำถามที่อนุมัติแล้วตรงตามสาขาและระดับความยาก' },
  ebNoQuestions: { en: 'No questions loaded. Click "Load questions".', th: 'ยังไม่มีคำถาม' },
  ebSelect: { en: 'Select', th: 'เลือก' },
  ebQuestion: { en: 'Question', th: 'คำถาม' },
  ebSelected: { en: 'Selected', th: 'เลือกแล้ว' },
  ebCreateExamBtn: { en: 'Create Exam', th: 'สร้างชุดข้อสอบ' },
  ebEnterName: { en: 'Please enter exam name', th: 'กรุณาใส่ชื่อข้อสอบ' },
  ebSelectSpec: { en: 'Please select specialty', th: 'กรุณาเลือกสาขา' },
  ebSelectSubspec: { en: 'Please select subspecialty', th: 'กรุณาเลือกสาขาย่อย' },
  ebMinQuestions: { en: 'Please set number of questions to at least 1', th: 'กรุณากำหนดจำนวนข้ออย่างน้อย 1 ข้อ' },
  ebSelectExact: { en: 'Please select exactly {0} questions (currently selected: {1})', th: 'กรุณาเลือกคำถามให้ครบ {0} ข้อ (เลือกแล้ว: {1})' },
  ebCreateFailed: { en: 'Create exam failed:', th: 'สร้างข้อสอบไม่สำเร็จ:' },
  ebLoadFailed: { en: 'Failed to load questions', th: 'โหลดคำถามไม่สำเร็จ' },
  ebMaxSelect: { en: 'You can select up to {0} questions.', th: 'เลือกได้สูงสุด {0} ข้อ' },

  // ExamsList
  elExams: { en: 'Exams', th: 'ข้อสอบ' },
  elSearch: { en: 'Search exams by name, specialty, difficulty...', th: 'ค้นหาข้อสอบตามชื่อ สาขา ระดับความยาก...' },
  elSelfPractice: { en: 'Create your own practice exam', th: 'กำหนดการสอบด้วยตัวเอง' },
  elExamName: { en: 'Exam name:', th: 'ชื่อข้อสอบ:' },
  elQuestions: { en: 'Questions:', th: 'จำนวนข้อ:' },
  elCreate: { en: 'Create', th: 'สร้าง' },
  elMyPractice: { en: 'My practice exam', th: 'ข้อสอบฝึกหัดของฉัน' },
  elNQuestions: { en: 'Questions', th: 'ข้อ' },
  elCreated: { en: 'Created:', th: 'สร้างเมื่อ:' },
  elDistribution: { en: 'Distribution:', th: 'สัดส่วน:' },
  elDiffScore: { en: 'Difficulty Score:', th: 'คะแนนความยาก:' },
  elTotal: { en: 'Total', th: 'รวม' },
  elAvg: { en: 'Avg', th: 'เฉลี่ย' },
  elSelection: { en: 'Selection:', th: 'รูปแบบ:' },
  elChosen: { en: 'chosen', th: 'ที่เลือก' },
  elTakeExam: { en: 'Take Exam', th: 'ทำข้อสอบ' },
  elNoExams: { en: 'No exams found', th: 'ไม่พบข้อสอบ' },
  elLoadFailed: { en: 'Failed to load exams', th: 'โหลดข้อสอบไม่สำเร็จ' },
  elNewExam: { en: 'New exam', th: 'ข้อสอบใหม่' },
  elExamCreated: { en: 'Exam created', th: 'สร้างข้อสอบสำเร็จ' },
  elCreateFailed: { en: 'Create failed — ensure you are authenticated', th: 'สร้างไม่สำเร็จ — กรุณาเข้าสู่ระบบก่อน' },

  // ExamTake
  etLoading: { en: 'Loading...', th: 'กำลังโหลด...' },
  etLoadFailed: { en: 'Failed to load exam', th: 'โหลดข้อสอบไม่สำเร็จ' },
  etDifficulty: { en: 'Difficulty level:', th: 'ระดับความยาก:' },
  etSelectionMode: { en: 'Selection mode:', th: 'รูปแบบการเลือกข้อสอบ:' },
  etPassingScore: { en: '✓ Minimum passing score:', th: '✓ คะแนนผ่านขั้นต่ำ:' },
  etNoQuestions: { en: '⚠ This exam has no questions — please contact administrator to add questions.', th: '⚠ ข้อสอบนี้ยังไม่มีคำถาม — กรุณาติดต่อผู้ดูแลระบบเพื่อเพิ่มคำถามในข้อสอบ' },
  etQuestionNum: { en: 'Question {0}', th: 'ข้อที่ {0}' },
  etYourAnswer: { en: 'Your answer', th: 'คำตอบของคุณ' },
  etClickZoom: { en: 'Click to enlarge', th: 'คลิกเพื่อขยาย' },
  etSubmit: { en: 'Submit Exam', th: 'ส่งข้อสอบ' },
  etSubmitFailed: { en: 'Failed to submit exam', th: 'ส่งข้อสอบไม่สำเร็จ' },
  etUnanswered: { en: 'Please answer all questions before submitting — {0} unanswered: Question {1}', th: 'กรุณาตอบให้ครบทุกข้อก่อนส่ง — ยังไม่ได้ตอบ {0} ข้อ: ข้อที่ {1}' },
  etAndMore: { en: ' and {0} more', th: ' และอีก {0} ข้อ' },

  // ExamResult
  erLoading: { en: 'Loading exam result...', th: 'กำลังโหลดผลสอบ...' },
  erLoadFailed: { en: 'Failed to load exam result:', th: 'ไม่สามารถโหลดผลสอบได้:' },
  erBackToExams: { en: 'Back to exam list', th: 'กลับหน้ารายการข้อสอบ' },
  erReportTitle: { en: 'Exam Result Report', th: 'รายงานผลการสอบ' },
  erExamInfo: { en: 'Exam Information', th: 'ข้อมูลข้อสอบ' },
  erStudentInfo: { en: 'Student Information', th: 'ข้อมูลผู้สอบ' },
  erExamDate: { en: 'Exam date:', th: 'วันที่สอบ:' },
  erPassed: { en: '✓ PASSED', th: '✓ ผ่าน (PASSED)' },
  erFailed: { en: '✗ FAILED', th: '✗ ไม่ผ่าน (FAILED)' },
  erCorrectOf: { en: 'Correct {0} of {1} questions', th: 'ตอบถูก {0} จาก {1} ข้อ' },
  erMinPassingScore: { en: 'Minimum passing score', th: 'คะแนนผ่านขั้นต่ำ' },
  erPassCriteria: { en: 'Pass criteria {0}%', th: 'เกณฑ์ผ่าน {0}%' },
  erAnswerDetails: { en: 'Answer Details', th: 'รายละเอียดคำตอบ' },
  erNo: { en: 'No.', th: 'ข้อ' },
  erQuestionCol: { en: 'Question', th: 'คำถาม' },
  erYourAnswer: { en: 'Your Answer', th: 'คำตอบของคุณ' },
  erCorrectAnswer: { en: 'Correct Answer', th: 'เฉลย' },
  erResult: { en: 'Result', th: 'ผลลัพธ์' },
  erNoAnswer: { en: '(no answer)', th: '(ไม่ได้ตอบ)' },
  erCorrectCount: { en: '✓ Correct {0}', th: '✓ ถูก {0} ข้อ' },
  erWrongCount: { en: '✗ Wrong {0}', th: '✗ ผิด {0} ข้อ' },
  erPrint: { en: '🖨️ Print Report', th: '🖨️ พิมพ์รายงาน' },
  erStudentHome: { en: 'Student Home', th: 'หน้าหลักนักศึกษา' },

  // ExamResultsDashboard
  erdTitle: { en: 'Exam Results Dashboard', th: 'แดชบอร์ดผลสอบ' },
  erdLoadFailed: { en: 'Failed to load results', th: 'โหลดผลสอบไม่สำเร็จ' },
  erdOverallStats: { en: 'Overall Statistics', th: 'สถิติภาพรวม' },
  erdTotalExams: { en: 'Total Exams Taken:', th: 'จำนวนครั้งที่สอบ:' },
  erdAvgScore: { en: 'Average Score:', th: 'คะแนนเฉลี่ย:' },
  erdPassRate: { en: 'Pass Rate (≥70%):', th: 'อัตราผ่าน (≥70%):' },
  erdSelectExam: { en: 'Select Exam to View Details', th: 'เลือกข้อสอบเพื่อดูรายละเอียด' },
  erdExamStats: { en: 'Exam Statistics', th: 'สถิติข้อสอบ' },
  erdStudents: { en: 'Students:', th: 'ผู้สอบ:' },
  erdPassed: { en: 'Passed (≥70%):', th: 'ผ่าน (≥70%):' },
  erdStudentResults: { en: 'Student Results', th: 'ผลการสอบของผู้เรียน' },
  erdStudent: { en: 'Student', th: 'ผู้สอบ' },
  erdScore: { en: 'Score', th: 'คะแนน' },
  erdCorrect: { en: 'Correct', th: 'ถูก' },
  erdDate: { en: 'Date', th: 'วันที่' },
  erdAction: { en: 'Action', th: 'จัดการ' },
  erdView: { en: 'View', th: 'ดู' },
  erdHistory: { en: 'History', th: 'ประวัติ' },
  erdDetailedAnswers: { en: 'Detailed Answers', th: 'รายละเอียดคำตอบ' },
  erdStudentAnswered: { en: 'Student answered:', th: 'ผู้สอบตอบ:' },
  erdCorrectAnswerIs: { en: 'Correct answer:', th: 'คำตอบที่ถูก:' },
  erdBlank: { en: '(blank)', th: '(ไม่ได้ตอบ)' },

  // ManageQuestionsExams
  mqTitle: { en: 'Manage questions & exams', th: 'จัดการคำถามและข้อสอบ' },
  mqQuestions: { en: 'Questions', th: 'คำถาม' },
  mqExams: { en: 'Exams', th: 'ข้อสอบ' },
  mqSearchQ: { en: 'Search questions by title, content, author, specialty...', th: 'ค้นหาคำถามตามชื่อ เนื้อหา ผู้สร้าง สาขา...' },
  mqSearchE: { en: 'Search exams by title, specialty, mode...', th: 'ค้นหาข้อสอบตามชื่อ สาขา โหมด...' },
  mqNoItems: { en: 'No items found', th: 'ไม่พบรายการ' },
  mqRejected: { en: 'REJECTED', th: 'ถูกส่งกลับ' },
  mqPending: { en: 'PENDING', th: 'รอตรวจสอบ' },
  mqApproved: { en: 'APPROVED', th: 'อนุมัติแล้ว' },
  mqMine: { en: 'MINE', th: 'ของฉัน' },
  mqBy: { en: 'by', th: 'โดย' },
  mqModFeedback: { en: '⚠ Moderator Feedback:', th: '⚠ ข้อเสนอแนะจากผู้ตรวจ:' },
  mqPreview: { en: '📋 Question Preview:', th: '📋 ตัวอย่างคำถาม:' },
  mqStem: { en: 'Stem:', th: 'โจทย์:' },
  mqDetails: { en: 'Details:', th: 'รายละเอียด:' },
  mqAnswerExpl: { en: 'Answer explanation:', th: 'อธิบายคำตอบ:' },
  mqChoices: { en: 'Choices:', th: 'ตัวเลือก:' },
  mqCorrect: { en: 'Correct', th: 'ถูกต้อง' },
  mqImages: { en: 'Images:', th: 'รูปภาพ:' },
  mqEditResubmit: { en: '✏ Edit & Resubmit', th: '✏ แก้ไขและส่งใหม่' },
  mqTitle2: { en: 'Title', th: 'ชื่อ' },
  mqQuestionStem: { en: 'Question (Stem)', th: 'โจทย์คำถาม' },
  mqDetail: { en: 'Detail', th: 'รายละเอียด' },
  mqAnswerExplLabel: { en: 'Correct Answer & Explanation', th: 'คำตอบที่ถูกและอธิบาย' },
  mqDifficulty: { en: 'Difficulty (1-5)', th: 'ระดับความยาก (1-5)' },
  mqChoicesLabel: { en: 'Choices (A–E)', th: 'ตัวเลือก (ก–จ)' },
  mqCorrectAnswer: { en: 'Correct Answer', th: 'คำตอบที่ถูก' },
  mqSpecialty: { en: 'Specialty', th: 'สาขาเฉพาะทาง' },
  mqSubspecialty: { en: 'Subspecialty', th: 'สาขาย่อย' },
  mqSelectSpec: { en: '-- select specialty --', th: '-- เลือกสาขา --' },
  mqSelectSubspec: { en: '-- select subspecialty --', th: '-- เลือกสาขาย่อย --' },
  mqDeleteImage: { en: 'Delete image', th: 'ลบรูป' },
  mqSelectionMode: { en: 'Selection mode:', th: 'รูปแบบเลือก:' },
  mqRandom: { en: 'Random', th: 'สุ่ม' },
  mqManualMode: { en: 'Manual', th: 'กำหนดเอง' },
  mqNumQuestions: { en: 'Num questions', th: 'จำนวนข้อ' },
  mqLoadQuestions: { en: 'Load questions', th: 'โหลดคำถาม' },
  mqChooseQuestions: { en: 'Choose questions to include in this exam', th: 'เลือกคำถามสำหรับข้อสอบนี้' },
  mqEdit: { en: 'Edit', th: 'แก้ไข' },
  mqOwnOnly: { en: 'You can only edit/delete your own items', th: 'คุณแก้ไข/ลบได้เฉพาะรายการของตนเอง' },
  mqConfirmDelete: { en: 'Confirm delete?', th: 'ยืนยันการลบ?' },
  mqNoStem: { en: '(no stem)', th: '(ไม่มีโจทย์)' },
  mqNoDetails: { en: '(no details)', th: '(ไม่มีรายละเอียด)' },
  mqNoExpl: { en: '(no explanation)', th: '(ไม่มีคำอธิบาย)' },
  mqSaved: { en: 'Saved successfully', th: 'บันทึกสำเร็จ' },
  mqSaveFailed: { en: 'Save failed:', th: 'บันทึกไม่สำเร็จ:' },
  mqLoadFailed: { en: 'Failed to load:', th: 'โหลดไม่สำเร็จ:' },
  mqLoadQFailed: { en: 'Failed to load questions', th: 'โหลดคำถามไม่สำเร็จ' },
  mqDeleted: { en: 'Deleted', th: 'ลบแล้ว' },
  mqDeleteFailed: { en: 'Delete failed:', th: 'ลบไม่สำเร็จ:' },
  mqImgUploadFailed: { en: 'Image upload failed:', th: 'อัปโหลดรูปไม่สำเร็จ:' },
  mqNewImgSelected: { en: 'New image selected:', th: 'เลือกรูปใหม่แล้ว:' },
  mqDiffLabel: { en: 'Difficulty:', th: 'ระดับความยาก:' },
  mqUseDistribution: { en: 'Use distribution', th: 'ใช้สัดส่วน' },
  mqDistAutoAdj: { en: 'Distribution (auto-adjusts to sum to 100%)', th: 'สัดส่วน (ปรับอัตโนมัติให้รวม 100%)' },
  mqTotal: { en: 'Total:', th: 'รวม:' },
  mqSelectedCount: { en: 'Selected:', th: 'เลือกแล้ว:' },
  mqUnspecified: { en: 'Unspecified', th: 'ไม่ระบุ' },
  mqTryNewImg: { en: 'Please try selecting a new image.', th: 'กรุณาเลือกรูปภาพใหม่' },
  mqSelectedBadge: { en: 'Selected', th: 'เลือกแล้ว' },
  mqDiff: { en: 'diff', th: 'ยาก' },

  // ModeratorQueue
  modTitle: { en: 'Moderator queue', th: 'คิวตรวจสอบคำถาม' },
  modLoadFailed: { en: 'Load failed — ensure you are logged in as admin/moderator', th: 'โหลดไม่สำเร็จ — กรุณาเข้าสู่ระบบเป็นผู้ตรวจ/ผู้ดูแล' },
  modNoPending: { en: 'No pending items', th: 'ไม่มีรายการรอตรวจ' },
  modDifficulty: { en: 'Difficulty:', th: 'ระดับความยาก:' },
  modQuestion: { en: 'Question:', th: 'คำถาม:' },
  modDetail: { en: 'Detail:', th: 'รายละเอียด:' },
  modImages: { en: 'Images:', th: 'รูปภาพ:' },
  modChoices: { en: 'Choices:', th: 'ตัวเลือก:' },
  modCorrect: { en: '✓ Correct', th: '✓ ถูกต้อง' },
  modAnswerExpl: { en: 'Answer Explanation:', th: 'อธิบายคำตอบ:' },
  modSpecialty: { en: 'Specialty:', th: 'สาขา:' },
  modApprove: { en: '✓ Approve', th: '✓ อนุมัติ' },
  modSendBack: { en: '↩ Send back', th: '↩ ส่งกลับ' },
  modApproved: { en: 'Approved', th: 'อนุมัติแล้ว' },
  modApproveFailed: { en: 'Approve failed', th: 'อนุมัติไม่สำเร็จ' },
  modSentBack: { en: 'Sent back to creator', th: 'ส่งกลับให้ผู้สร้างแล้ว' },
  modSendBackFailed: { en: 'Send back failed', th: 'ส่งกลับไม่สำเร็จ' },
  modFeedback: { en: 'Feedback to creator (optional):', th: 'ข้อเสนอแนะถึงผู้สร้าง (ไม่บังคับ):' },

  // StudentDashboard
  sdTitle: { en: 'Self practice / Student', th: 'ฝึกหัดด้วยตนเอง / นักศึกษา' },
  sdMyProgress: { en: 'My progress', th: 'ความก้าวหน้า' },
  sdFullStats: { en: 'Full stats', th: 'สถิติทั้งหมด' },
  sdAvgScore: { en: 'Average score', th: 'คะแนนเฉลี่ย' },
  sdLastScore: { en: 'Last score', th: 'คะแนนล่าสุด' },
  sdImprovement: { en: 'Improvement', th: 'พัฒนาการ' },
  sdNumQuestions: { en: 'Number of questions:', th: 'จำนวนข้อ:' },
  sdStartExam: { en: 'Start self-exam', th: 'เริ่มทำข้อสอบ' },
  sdSubmit: { en: 'Submit', th: 'ส่ง' },
  sdYourAnswer: { en: 'Your answer', th: 'คำตอบของคุณ' },
  sdScore: { en: 'Score:', th: 'คะแนน:' },
  sdDifficulty: { en: 'difficulty', th: 'ความยาก' },

  // StudentStats
  ssTitle: { en: '📊 Performance Report', th: '📊 รายงานผลการเรียน' },
  ssBack: { en: 'Back', th: 'กลับ' },
  ssTotalExams: { en: 'Total Exams Taken', th: 'จำนวนครั้งที่สอบ' },
  ssAvgScore: { en: 'Average Score', th: 'คะแนนเฉลี่ย' },
  ssBestScore: { en: 'Best Score', th: 'คะแนนสูงสุด' },
  ssPassRate: { en: 'Pass Rate (≥70%)', th: 'อัตราผ่าน (≥70%)' },
  ssTrend: { en: 'Trend:', th: 'แนวโน้ม:' },
  ssImproving: { en: '✓ Improving by +{0}%', th: '✓ ดีขึ้น +{0}%' },
  ssDeclining: { en: 'Declining by {0}%', th: 'ลดลง {0}%' },
  ssCompareHalf: { en: '(comparing first half to second half of attempts)', th: '(เปรียบเทียบครึ่งแรกกับครึ่งหลังของการสอบ)' },
  ssScoreTrend: { en: 'Score Trend Visualization (Last 12 Attempts)', th: 'กราฟคะแนน (12 ครั้งล่าสุด)' },
  ssNoAttempts: { en: 'No attempts yet.', th: 'ยังไม่มีการสอบ' },
  ssPerformByExam: { en: 'Performance by Exam Type', th: 'ผลตามประเภทข้อสอบ' },
  ssAttempts: { en: 'Attempts', th: 'จำนวนครั้ง' },
  ssAvg: { en: 'Avg Score', th: 'คะแนนเฉลี่ย' },
  ssHistory: { en: '📋 Detailed Exam History', th: '📋 ประวัติการสอบ' },
  ssDate: { en: 'Date', th: 'วันที่' },
  ssExam: { en: 'Exam', th: 'ข้อสอบ' },
  ssScore: { en: 'Score', th: 'คะแนน' },
  ssStatus: { en: 'Status', th: 'สถานะ' },
  ssAction: { en: 'Action', th: 'จัดการ' },
  ssPassed: { en: '✓ PASSED', th: '✓ ผ่าน' },
  ssFailed: { en: '✗ FAILED', th: '✗ ไม่ผ่าน' },
  ssLoadFailed: { en: 'Failed to load stats', th: 'โหลดสถิติไม่สำเร็จ' },
  ssNoStats: { en: 'No stats available', th: 'ไม่มีข้อมูลสถิติ' },
  ssNotAuth: { en: 'Not authenticated. Please login again.', th: 'ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบใหม่' },
  ssPdfFailed: { en: 'PDF generation failed: Empty response', th: 'สร้าง PDF ไม่สำเร็จ' },
  ssPdfDownloadFailed: { en: 'PDF download failed:', th: 'ดาวน์โหลด PDF ไม่สำเร็จ:' },

  // ClinicianDashboard
  cdTitle: { en: '📊 Clinician Dashboard — Exam Analytics', th: '📊 แดชบอร์ดอาจารย์แพทย์ — วิเคราะห์ข้อสอบ' },
  cdBackToManage: { en: 'Back to Manage', th: 'กลับจัดการ' },
  cdOverallStats: { en: 'Overall Stats', th: 'สถิติภาพรวม' },
  cdStudentPerf: { en: 'Student Performance', th: 'ผลการเรียนรู้' },
  cdExamAnalysis: { en: 'Exam Analysis', th: 'วิเคราะห์ข้อสอบ' },
  cdLoadingData: { en: 'Loading data...', th: 'กำลังโหลดข้อมูล...' },
  cdPlatformStats: { en: 'Platform-Wide Statistics', th: 'สถิติทั้งระบบ' },
  cdTotalAttempts: { en: 'Total Exam Attempts', th: 'จำนวนการสอบทั้งหมด' },
  cdUniqueStudents: { en: 'Unique Students', th: 'จำนวนผู้เรียน' },
  cdAvgScore: { en: 'Average Score', th: 'คะแนนเฉลี่ย' },
  cdPassRate: { en: 'Pass Rate (≥70%)', th: 'อัตราผ่าน (≥70%)' },
  cdHighestScore: { en: 'Highest Score', th: 'คะแนนสูงสุด' },
  cdLowestScore: { en: 'Lowest Score', th: 'คะแนนต่ำสุด' },
  cdScoreDist: { en: 'Score Distribution', th: 'การกระจายคะแนน' },
  cdPassPerf: { en: 'Passing Performance', th: 'ผลการผ่าน' },
  cdPassedOf: { en: 'Passed:', th: 'ผ่าน:' },
  cdPassRateLabel: { en: 'Pass Rate:', th: 'อัตราผ่าน:' },
  cdStudentTrends: { en: 'Student Performance Trends', th: 'แนวโน้มผลการเรียนรู้' },
  cdSelectStudent: { en: 'Select Student:', th: 'เลือกผู้เรียน:' },
  cdChooseStudent: { en: '-- Choose a student --', th: '-- เลือกผู้เรียน --' },
  cdExamsTaken: { en: 'Exams Taken', th: 'จำนวนการสอบ' },
  cdBestScore: { en: 'Best Score', th: 'คะแนนสูงสุด' },
  cdTrend: { en: 'Trend', th: 'แนวโน้ม' },
  cdScoreProg: { en: 'Score Progression', th: 'กราฟคะแนน' },
  cdExamHistory: { en: 'Exam History', th: 'ประวัติการสอบ' },
  cdDate: { en: 'Date', th: 'วันที่' },
  cdExam: { en: 'Exam', th: 'ข้อสอบ' },
  cdScore: { en: 'Score', th: 'คะแนน' },
  cdStatus: { en: 'Status', th: 'สถานะ' },
  cdPassed: { en: '✓ PASSED', th: '✓ ผ่าน' },
  cdFailed: { en: '✗ FAILED', th: '✗ ไม่ผ่าน' },
  cdExamPerfAnalysis: { en: 'Exam Performance Analysis', th: 'วิเคราะห์ผลข้อสอบ' },
  cdSelectExam: { en: 'Select Exam:', th: 'เลือกข้อสอบ:' },
  cdChooseExam: { en: '-- Choose an exam --', th: '-- เลือกข้อสอบ --' },
  cdStudentsAttempted: { en: 'Students Attempted', th: 'ผู้เข้าสอบ' },
  cdPassedCount: { en: 'Passed (≥70%)', th: 'ผ่าน (≥70%)' },
  cdStudentResults: { en: 'Student Results', th: 'ผลการสอบของผู้เรียน' },
  cdStudentName: { en: 'Student Name', th: 'ชื่อผู้เรียน' },
  cdDateTaken: { en: 'Date Taken', th: 'วันที่สอบ' },
  cdLoadFailed: { en: 'Failed to load exam results:', th: 'โหลดผลสอบไม่สำเร็จ:' },
  cdLoadStudentFailed: { en: 'Failed to load student details:', th: 'โหลดข้อมูลผู้เรียนไม่สำเร็จ:' },
  cdStudents: { en: 'students', th: 'คน' },

  // AdminSpecialtyManagement
  asmBackToAdmin: { en: '← Back to Admin', th: '← กลับหน้าจัดการ' },
  asmTitle: { en: 'Specialty Management', th: 'จัดการสาขาเฉพาะทาง' },
  asmEditSpec: { en: 'Edit Specialty', th: 'แก้ไขสาขา' },
  asmAddSpec: { en: 'Add New Specialty', th: 'เพิ่มสาขาใหม่' },
  asmSpecName: { en: 'Specialty name', th: 'ชื่อสาขา' },
  asmSubSpecs: { en: 'Sub-specialties:', th: 'สาขาย่อย:' },
  asmAddSub: { en: 'Add sub-specialty', th: 'เพิ่มสาขาย่อย' },
  asmAdd: { en: 'Add', th: 'เพิ่ม' },
  asmUpdate: { en: 'Update', th: 'อัปเดต' },
  asmSpecList: { en: 'Specialty List', th: 'รายการสาขา' },
  asmSubSpecsCol: { en: 'Sub-specialties', th: 'สาขาย่อย' },
  asmActions: { en: 'Actions', th: 'จัดการ' },
  asmDeleteSubConfirm: { en: 'Delete this sub-specialty?', th: 'ลบสาขาย่อยนี้?' },
  asmDeleteSpecConfirm: { en: 'Delete this specialty and all its subspecialties?', th: 'ลบสาขานี้และสาขาย่อยทั้งหมด?' },
  asmUpdated: { en: 'Updated successfully', th: 'อัปเดตสำเร็จ' },
  asmAdded: { en: 'Added successfully', th: 'เพิ่มสำเร็จ' },
  asmDeleted: { en: 'Specialty deleted', th: 'ลบสาขาสำเร็จ' },
  asmSubDeleted: { en: 'Sub-specialty deleted and saved', th: 'ลบสาขาย่อยและบันทึกแล้ว' },
  asmLoadFailed: { en: 'Failed to load specialties', th: 'โหลดสาขาไม่สำเร็จ' },
  asmSaveFailed: { en: 'Error saving', th: 'บันทึกไม่สำเร็จ' },
  asmDeleteFailed: { en: 'Error deleting specialty', th: 'ลบสาขาไม่สำเร็จ' },
  asmSaveAfterDeleteFailed: { en: 'Error saving after delete', th: 'บันทึกหลังลบไม่สำเร็จ' },
  asmSaveAfterDelFailed: { en: 'Error saving after delete', th: 'บันทึกหลังลบไม่สำเร็จ' },

  // Shared
  noHospitalsFound: { en: 'No hospitals found', th: 'ไม่พบโรงพยาบาล' },
  noProvincesFound: { en: 'No provinces found', th: 'ไม่พบจังหวัด' },
  passRateLabel: { en: 'Pass Rate', th: 'อัตราผ่าน' },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'th')

  function toggleLang() {
    const next = lang === 'en' ? 'th' : 'en'
    setLang(next)
    localStorage.setItem('lang', next)
  }

  function t(key) {
    const entry = translations[key]
    if (!entry) return key
    return entry[lang] || entry['en'] || key
  }

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
